live_config_reload = true

import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]

# Fonts
[font]
size = 14.0

[font.normal]
family = "JetBrainsMono"
style = "Bold"

[env]
TERM = "xterm-256color"
