
# Fonts
[font]
size = 18.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[env]
TERM = "xterm-256color"

[general]
live_config_reload = true

import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]
