## Current active window
bindsym --release Print exec scrot -u '/tmp/screenshot_%Y%m%d_%H%M%S.png' -e 'xclip -selection clipboard -t image/png -i $f'

## Area selection
bindsym --release Shift+Print exec scrot -s '/tmp/screenshot_%Y%m%d_%H%M%S.png' -e 'xclip -selection clipboard -t image/png -i $f'
