require 'config.options'

require 'custom.lazy'
require 'custom.telescope'

require 'config.highlight_yank'
require 'config.diagnostic'
require 'config.filetypes'
require 'config.floaterminal'
require 'config.fugitive'
require 'config.keymap'
require 'config.menu'
require 'config.multigrep'
require 'config.terminal'
require 'config.title'
require 'config.lsp'
